### ISSUE TITLE
After recent changes I get this error messages in console

### ISSUE THREAD

**Issue by XCanG** [cniw/mpv-discordRPC#10]
* mpv-x86_64-20200426-git-640db1e
* mpv-discordRPC-1.4.1-UNKNOWN-win

Log (colorized):
```diff
- Can't load unknown script: C:\Users\X4\AppData\Roaming/mpv/scripts/mpv-discordRPC_pypresence.py
! [mpv_discordRPC] script-opts/mpv_discordRPC.conf:21 unknown key mpv_version, ignoring
[mpv_discordRPC] Discord Rich Presence integration for mpv Media Player
[mpv_discordRPC] Upstream: https://github.com/cniw/mpv-discordRPC
[mpv_discordRPC2] Discord Rich Presence integration for mpv Media Player
[mpv_discordRPC] Version: 1.4.1
[mpv_discordRPC2] Upstream: https://github.com/cniw/mpv-discordRPC
[mpv_discordRPC2] Version: 1.4.1-UNKNOWN
```
I have no issues with using python version (tried it as well before), but I still use lua, however mpv now after update throwing errors about this file.
Also it have some problems with `mpv_version` variable, may be need to rename it?

**Comment by cniw** [comment]
@XCanG sorry, slow response.

It seems two scripts running
- old one
```
[mpv_discordRPC] Discord Rich Presence integration for mpv Media Player
[mpv_discordRPC] Upstream: https://github.com/cniw/mpv-discordRPC
[mpv_discordRPC] Version: 1.4.1
```
- new
```
[mpv_discordRPC2] Discord Rich Presence integration for mpv Media Player
[mpv_discordRPC2] Upstream: https://github.com/cniw/mpv-discordRPC
[mpv_discordRPC2] Version: 1.4.1-UNKNOWN
```

```[mpv_discordRPC] script-opts/mpv_discordRPC.conf:21 unknown key mpv_version, ignoring```
this error message caused by the old script trying to load the new file configuration

So the solution is just need to delete the old script file, it located at `scripts/mpv-discordRPC.lua`

New script file moved to `scripts/mpv-discordRPC/main.lua`, related commit https://github.com/cniw/mpv-discordRPC/commit/c9f7443b8d13df0b80d0e329490bbd798f566390


hopefully this can solve your problem.

**Comment by XCanG** [comment]
Yeh, looks like script moved into subfolder and I didn't notice that. Remove old files and error is gone.
