### ISSUE TITLE
module 'ffi' not found

### ISSUE THREAD

**Issue by blissfulVoid** [cniw/mpv-discordRPC#17]
I'm having trouble running this, when i try to run mpv, it shows me this:

`[mpv_discordRPC] Lua error: ...su/.config/mpv/scripts/mpv-discordRPC/lua-discordRPC.lua:1: module 'ffi' not found:
[mpv_discordRPC]        no field package.preload['ffi']
[mpv_discordRPC]        no file '/home****/.config/mpv/scripts/mpv-discordRPC/ffi.lua'
[mpv_discordRPC]        no file '/usr/share/lua/5.2/ffi.lua'
[mpv_discordRPC]        no file '/usr/share/lua/5.2/ffi/init.lua'
[mpv_discordRPC]        no file '/usr/lib/lua/5.2/ffi.lua'
[mpv_discordRPC]        no file '/usr/lib/lua/5.2/ffi/init.lua'
[mpv_discordRPC]        no file '/usr/lib/lua/5.2/ffi.so'
[mpv_discordRPC]        no file '/usr/lib/lua/5.2/loadall.so'`

**Comment by RivenSkaye** [comment]
This is most probably because it was written with a version of mpv built against LuaJIT instead of Lua 5.2 and the dependency wasn't thought to be missing on versions of mpv built against Lua 5.2.

My advice would be to find and install the `ffi` module elsewhere. If you have Lua + LuaRocks installed on your system, you can probably get it there and install it as a global package
