### ISSUE TITLE
mpv.net support

### ISSUE THREAD

**Issue by 0ANIMEFREAK0** [cniw/mpv-discordRPC#3]
can u make it so it woks with mpv.net 

https://github.com/stax76/mpv.net

**Comment by cniw** [comment]
yeah it work already with `lua-discordRPC` wrapper but not with `pypresence` because it use Python >= 3.5 while mpv.net implemented with IronPython which uses Python 2.7.

So do this:
- to install this script you can use `install-win.bat` and point the path of installation to mpv.net directory e.g. `D:\Applications\mpv.net-portable-x64-5.3.0.0`, make sure `discord-rpc.dll` in same folder with `mpvnet.exe`
- change keep/set config to `rpc_wrapper=lua-discordRPC`
- if you got error message, *pypresence is missing* just delete file `mpv-discordRPC_pypresence.py` cause it autoload by mpv.net
