### ISSUE TITLE
ImportError: No module named pypresence

### ISSUE THREAD

**Issue by Admiral124** [cniw/mpv-discordRPC#6]
Hello, 
I am trying to use this on a fresh install of Kubuntu 19.10 but for some reason pypresence is giving me issues. When running mpv from the terminal, I can see the script is giving this error over and over: 
`Traceback (most recent call last):
  File "/home/user/.config/mpv/scripts/mpv-discordRPC/python-pypresence.py", line 6, in <module>
    import pypresence
ImportError: No module named pypresence
`
However, pypresence IS installed. Python 3 is at version 3.7.5. and `pip3 list` shows pypresence 3.3.2 is there. Further, if I open a terminal and manually run python3 and then import pypresence, it works just fine.

**Comment by cniw** [comment]
FYI python 2 will faces official end-of-life in 2020. So you got that error because Ubuntu derivative also still use python 2 as default.
But currently in master branch i was change it at this [commit](https://github.com/cniw/mpv-discordRPC/commit/4692413931f84051dbc120ef8566eefff23e94be#diff-5db4f45a65cbbd0b631bcb000f2ea41e), i asume that default `python` command is referring to `python3`.

To fix your issue you can change back file `~/.config/mpv/scripts/mpv-discordRPC.lua` at line [233](https://github.com/cniw/mpv-discordRPC/blob/master/mpv-discordRPC.lua#L233) and [236](https://github.com/cniw/mpv-discordRPC/blob/master/mpv-discordRPC.lua#L236) from `python` to `python3` like before.

**Comment by Admiral124** [comment]
Thanks, that did seem to solve that problem and I'm not seeing any more error messages in the terminal, however it's still not working properly... the "playing mpv Media Player" status on Discord cycles on and off seemingly at random, but it never stays for more than 10 seconds or so while playing a video.

**Comment by Admiral124** [comment]
I switched back to Debian stable and it seems to be doing the same thing on this as well. However, I noticed that while running mpv, the pypresence script seemingly keeps executing over and over again which might be what is causing this issue (See [here](https://files.catbox.moe/1670wj.png)). As you can see, mpv isn't even running anymore, but these processes aren't stopping. Since there are no actually errors in the log though, I can't really give any more insight into this, so I will close the issue.
